### ISSUE TITLE
CRS Info widget

### ISSUE THREAD

**Issue by HuidaeCho** [HuidaeCho/projpicker#37]
![image](https://user-images.githubusercontent.com/7456117/124834874-6d5a2700-df4e-11eb-98d5-d63b49d3cc6c.png)

@ocsmit Is CRS Info too small for you? I hardcoded its height to 125, but I guess it's system-dependent, so I need to grow it a little bit.

Also, is there a way to add a small padding to the left of the info text other than adding a space to the text itself (ugly...)?

Also, as is CRS Info is not copyable. Is there a better widget type, like `<textarea>` that can be read-only?

**Comment by ocsmit** [comment]
> @ocsmit Is CRS Info too small for you? I hardcoded its height to 125, but I guess it's system-dependent, so I need to grow it a little bit. 

CRS info is too small for me. Could be my system font style/size. Maybe a way to make it scale based of system text info. Scroll bar in TextCtrl widget (mentioned below) makes it less important though.

> Also, is there a way to add a small padding to the left of the info text other than adding a space to the text itself (ugly...)?

The text padding / positioning is something I have been struggling to figure out because no matter what positioning or alignment I change, it stays the same. I really don't want to add spaces/tabs in front of the text. There has to be a way to some sort of offset or padding, but I havent been able to find it. 

> Also, as is CRS Info is not copyable. Is there a better widget type, like `<textarea>` that can be read-only?

I just changed the text to the TextCtrl widget in 1495d97 which adds selection and copying and the aforementioned scrollbar for the text.

**Comment by HuidaeCho** [comment]
You found TextCtrl at the same time as I did! `SetMargins()` of this control didn't solve padding. I don't know what this is for then. :(

**Comment by HuidaeCho** [comment]
Please try https://github.com/HuidaeCho/projpicker/commit/9bf8c90d00f32ccbedf26609f2ec13ea3ec20b6d and let me know if the TextCtrl is the right size with no scrollbar.

**Comment by ocsmit** [comment]
> Please try [9bf8c90](https://github.com/HuidaeCho/projpicker/commit/9bf8c90d00f32ccbedf26609f2ec13ea3ec20b6d) and let me know if the TextCtrl is the right size with no scrollbar.

Works!
